### ISSUE TITLE
Error calling command 'scan': module 'yaml' has no attribute 'CLoader'

### ISSUE THREAD

**Issue by sdcampbell** [byt3bl33d3r/WitnessMe#9] opened 2019-11-27 21:30 UTC
The working environment is Mac OS.

WMDB ≫ scan 1
Traceback (most recent call last):
  File "wmdb.py", line 239, in cmdloop
    await self.scan()
  File "wmdb.py", line 197, in scan
    self.signatures.load()
  File "/Users/[redacted]/opt/WitnessMe/witnessme/signatures.py", line 15, in load
    self.signatures.append(yaml.load(sig, Loader=yaml.CLoader))
AttributeError: module 'yaml' has no attribute 'CLoader'
Error calling command 'scan': module 'yaml' has no attribute 'CLoader'

**Comment by sdcampbell** [comment] 2019-11-28 10:08
I also tested on a fresh Kali virtual machine with the same result.

**Comment by byt3bl33d3r** [comment] 2019-11-29 19:20
What Python version are you using?

**Comment by sdcampbell** [comment] 2019-11-30 20:29
I had the same error on three of my systems:

On my Mac, the Python version is 3.7.4.
On Kali 2019.4, the Python version is 3.7.5.
I also tried the Dockerized version (https://github.com/faun88/WitnessMe) which used 3.7.

I installed WitnessMe as per your instructions using pipenv.

By the way, thanks for the work you put into CrackMapExec and WitnessMe!

**Comment by byt3bl33d3r** [comment] 2019-12-03 18:11
@sdcampbell not exactly sure what the issue is here, cause it works for me on Mac. Are you running it in a virtualenv? Can you paste the output of `pip freeze` here? 
Thanks

**Comment by sdcampbell** [comment] 2019-12-03 21:18
I am running it in a virtualenv on Mac using pipenv. I installed and ran it using the exact same commands as found in the project's README. Keep in mind that I had the same error after installing it on a fresh Kali 2019.4 virtual machine.

pip freeze:

aiosqlite==0.10.0
appdirs==1.4.3
astroid==2.2.5
beautifulsoup4==4.8.0
certifi==2019.6.16
colorama==0.4.1
imgcat==0.4.0
isort==4.3.21
lazy-object-proxy==1.4.2
mccabe==0.6.1
pipenv==2018.11.26
pirate-get==0.3.3
prompt-toolkit==2.0.10
pyee==6.0.0
pylint==2.3.1
pyperclip==1.7.0
pyppeteer==0.0.25
PyYAML==5.1.2
six==1.13.0
soupsieve==1.9.3
termcolor==1.1.0
terminaltables==3.1.0
tqdm==4.38.0
typed-ast==1.4.0
urllib3==1.25.7
veryprettytable==0.8.1
virtualenv==16.7.4
virtualenv-clone==0.5.3
wcwidth==0.1.7
websockets==8.1
wrapt==1.11.2
xmltodict==0.12.0

**Comment by shaunography** [comment] 2019-12-12 09:52
I am getting the same error on Kali

pip freeze (within the pipenv)

aiosqlite==0.10.0
appdirs==1.4.3
imgcat==0.4.0
pkg-resources==0.0.0
prompt-toolkit==2.0.10
pyee==6.0.0
pyppeteer==0.0.25
PyYAML==5.1.2
six==1.13.0
terminaltables==3.1.0
tqdm==4.38.0
urllib3==1.25.7
wcwidth==0.1.7
websockets==8.1
xmltodict==0.12.0

**Comment by byt3bl33d3r** [comment] 2020-07-06 16:11
Fixed in latest update.

Cheers

**Closed by byt3bl33d3r** 2020-07-06 16:11 UTC
Labels: Moar info required tovarish
